services:
  postgres:
    image: postgres:15
    container_name: sofa-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: sofa_db
      POSTGRES_USER: sofa_db
      POSTGRES_PASSWORD: quocbao1123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
